version: "3"

services:
  zipkin:
    image: openzipkin/zipkin
    networks:
      - hidrone_net
    ports:
      - 9411:9411

networks:
  hidrone_net:
    external:
      name: hidrone_net
