version: '3.1'

services:
  centos_dev:
    build: ./
    container_name: centos_dev
    networks:
      - app_net
    volumes:
      - ~/server/go/demo:/root/demo/ # demo代码
      - ${WORKSPACE_CODE}:/root/workspace/ # 项目代码
      - ${WORKSPACE_CODE}/hidrone/svc/recognition/rtc/libs:/root/rtc_recognize/rtc/libs # /root/rtc_recognize为镜像打包固定目录
      - ${WORKSPACE_CODE}/hidrone/svc/recognition/face/libs:/root/rtc_recognize/face/libs
      - /data/hiDrone/recognize:/data/recognize
    tty: true
    environment:
      MICRO_REGISTRY: ${MICRO_REGISTRY}
      MICRO_REGISTRY_ADDRESS: ${MICRO_REGISTRY_ADDRESS}
    mac_address: 02:42:ac:12:00:02
    ports:
      - 6060:6060

networks:
  app_net:
    external:
      name: hidrone_net
